server:
  port: 8080

spring:
  application:
    name: mail-sender

  datasource:
    url: jdbc:h2:mem:maildb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계에서만 update 사용
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import: classpath:application-secret.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: gipark@nineonesoft.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html       # 접속 경로 단축 (기본: /swagger-ui/index.html)
    tags-sorter: alpha           # 태그 정렬 순서
    operations-sorter: method    # API 메서드 정렬 순서
    disable-swagger-default-url: true # 기본 petstore URL 비활성화
    doc-expansion: none          # 초기 로딩 시 다 접어두기 (가독성 확보)
  api-docs:
    path: /api-docs              # OpenAPI JSON 문서 경로

mail:
  default-from: no-reply@example.com
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 1000
    thread-name-prefix: "MAIL-ASYNC-"
  dispatch:
    limit: 100  # 기본값
  scheduler:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
